#name: Trigger auto deployment for containerapps
#
## When this action will be executed
#on:
#  # Automatically trigger it when detected changes in repo
#  push:
#    branches:
#      [ main ]
#
#  # Allow mannually trigger
#  workflow_dispatch:
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout to the branch
#        uses: actions/checkout@v2
#        with:
#          path: main
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Log in to container registry
#        uses: docker/login-action@v1
#        with:
#          registry: esntumi.azurecr.io
#          username: ${{ secrets.REGISTRY_USERNAME }}
#          password: ${{ secrets.REGISTRY_PASSWORD }}
#
#      - name: Build and push container image to registry
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: esntumi.azurecr.io/events:${{ github.sha }}
#          file: events/Dockerfile
#
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Azure Login
#        uses: azure/login@v1
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}
#
#
#      - name: Deploy to containerapp
#        uses: azure/CLI@v1
#        with:
#          inlineScript: |
#            echo "Installing containerapp extension"
#            az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.0-py2.py3-none-any.whl --yes
#            echo "Starting Deploying"
#            az containerapp update -n events -g tumi-container -i esntumi.azurecr.io/events:${{ github.sha }} --registry-login-server esntumi.azurecr.io --registry-username  ${{ secrets.REGISTRY_USERNAME }} --registry-password ${{ secrets.REGISTRY_PASSWORD }} --debug
